import { ReactNode } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Sparkles, Zap, ShieldCheck } from "lucide-react";
import { CreatorCredit } from "@/components/CreatorCredit";

const ASSET = import.meta.env.BASE_URL;
const LOGO = `${ASSET}aethon-logo.png`;

const SHOWCASE = [
  { src: "showcase/gaming.png", label: "Gaming" },
  { src: "showcase/anime.png", label: "Anime" },
  { src: "showcase/cinematic.png", label: "Cinematic" },
  { src: "showcase/stream.png", label: "Streaming" },
  { src: "showcase/motivation.png", label: "Motivation" },
  { src: "showcase/abstract.png", label: "Editorial" },
];

function ShowcaseCard({ src, label }: { src: string; label: string }) {
  return (
    <div className="relative overflow-hidden rounded-2xl border border-white/10 shadow-[0_18px_40px_-20px_rgba(0,0,0,0.9)]">
      <img
        src={`${ASSET}${src}`}
        alt=""
        draggable={false}
        loading="lazy"
        className="w-full aspect-[3/4] object-cover select-none"
      />
      <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/5 to-transparent" />
      <span className="absolute bottom-2.5 left-2.5 rounded-md bg-black/45 px-2 py-0.5 text-[10px] font-mono uppercase tracking-[0.18em] text-white/85 backdrop-blur-sm">
        {label}
      </span>
    </div>
  );
}

function ShowcaseColumn({
  items,
  direction,
  reduce,
}: {
  items: { src: string; label: string }[];
  direction: "up" | "down";
  reduce: boolean;
}) {
  const loop = [...items, ...items];
  return (
    <motion.div
      className="flex flex-col gap-4"
      animate={
        reduce
          ? undefined
          : { y: direction === "up" ? ["0%", "-50%"] : ["-50%", "0%"] }
      }
      transition={
        reduce
          ? undefined
          : { duration: 30, ease: "linear", repeat: Infinity }
      }
    >
      {loop.map((it, i) => (
        <ShowcaseCard key={`${it.label}-${i}`} src={it.src} label={it.label} />
      ))}
    </motion.div>
  );
}

const TRUST = [
  { icon: Sparkles, label: "Free forever" },
  { icon: ShieldCheck, label: "No credit card" },
  { icon: Zap, label: "Gemini-powered" },
];

export function AuthLayout({ children }: { children: ReactNode }) {
  const reduce = useReducedMotion() ?? false;
  const colA = [SHOWCASE[0], SHOWCASE[2], SHOWCASE[4]];
  const colB = [SHOWCASE[1], SHOWCASE[3], SHOWCASE[5]];

  return (
    <div className="relative min-h-[100dvh] w-full overflow-hidden bg-[#07060c] text-white">
      {/* Ambient atmosphere */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div
          className="absolute -top-[15%] -left-[10%] h-[60%] w-[55%] rounded-full blur-[150px]"
          style={{ background: "radial-gradient(circle, rgba(124,58,237,0.30) 0%, transparent 70%)" }}
        />
        <div
          className="absolute -bottom-[18%] -right-[10%] h-[55%] w-[50%] rounded-full blur-[140px]"
          style={{ background: "radial-gradient(circle, rgba(236,72,153,0.22) 0%, transparent 70%)" }}
        />
        <div
          className="absolute left-1/2 top-1/2 h-[70%] w-[70%] -translate-x-1/2 -translate-y-1/2 rounded-full blur-[180px] opacity-60"
          style={{ background: "radial-gradient(circle, rgba(6,182,212,0.08) 0%, transparent 70%)" }}
        />
      </div>

      <div className="relative z-10 grid min-h-[100dvh] lg:h-[100dvh] lg:grid-cols-2">
        {/* LEFT — cinematic brand + creator showcase */}
        <div className="relative hidden h-[100dvh] flex-col overflow-hidden border-r border-white/[0.06] lg:flex">
          <div className="px-10 pb-6 pt-12 xl:px-14">
            <img
              src={LOGO}
              alt="AETHON"
              draggable={false}
              className="h-9 w-auto select-none object-contain"
            />
            <p className="mt-6 font-mono text-[11px] uppercase tracking-[0.32em] text-white/45">
              The Cinematic AI Creator OS
            </p>
            <h1 className="mt-4 max-w-md text-[2.6rem] font-black leading-[1.05] tracking-tight">
              Create{" "}
              <span className="bg-gradient-to-r from-violet-300 via-fuchsia-300 to-pink-300 bg-clip-text text-transparent">
                scroll-stopping
              </span>{" "}
              content.
            </h1>
            <p className="mt-4 max-w-md text-sm leading-relaxed text-white/55">
              Captions, titles, hashtags and cinematic thumbnails — generated by
              AI and tuned for gamers, editors and creators. Sign in to open your
              workspace.
            </p>
          </div>

          {/* Showcase wall */}
          <div className="relative min-h-0 flex-1 px-10 xl:px-14">
            <div
              className="grid h-full grid-cols-2 gap-4"
              style={{
                WebkitMaskImage:
                  "linear-gradient(to bottom, transparent, black 12%, black 86%, transparent)",
                maskImage:
                  "linear-gradient(to bottom, transparent, black 12%, black 86%, transparent)",
              }}
            >
              <div className="h-full overflow-hidden">
                <ShowcaseColumn items={colA} direction="up" reduce={reduce} />
              </div>
              <div className="h-full overflow-hidden pt-10">
                <ShowcaseColumn items={colB} direction="down" reduce={reduce} />
              </div>
            </div>
          </div>

          {/* Trust row */}
          <div className="flex flex-wrap items-center gap-2.5 px-10 pb-12 pt-6 xl:px-14">
            {TRUST.map(({ icon: Icon, label }) => (
              <span
                key={label}
                className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs font-medium text-white/70 backdrop-blur-sm"
              >
                <Icon className="h-3.5 w-3.5 text-violet-300" />
                {label}
              </span>
            ))}
          </div>
        </div>

        {/* RIGHT — auth form (scroll-safe: centers when room, scrolls when not) */}
        <div className="relative flex min-h-[100dvh] flex-col items-center overflow-y-auto px-5 py-12 sm:px-8 lg:h-[100dvh]">
          <div className="my-auto flex w-full flex-col items-center">
            {/* Compact brand header (mobile only) */}
            <div className="mb-8 flex flex-col items-center lg:hidden">
              <img
                src={LOGO}
                alt="AETHON"
                draggable={false}
                className="h-8 w-auto select-none object-contain"
              />
              <p className="mt-3 font-mono text-[10px] uppercase tracking-[0.3em] text-white/45">
                The Cinematic AI Creator OS
              </p>
            </div>

            <motion.div
              initial={{ opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className="w-full max-w-[440px]"
            >
              {children}
            </motion.div>

            <p className="mt-8 max-w-xs text-center text-xs leading-relaxed text-white/35">
              By continuing you agree to keep creating cinematic content. Free
              forever — no credit card required.
            </p>
            <CreatorCredit tone="dark" className="mt-5" />
          </div>
        </div>
      </div>
    </div>
  );
}
